import 'dart:convert';
import 'dart:typed_data';

import 'package:archive/archive.dart';
import 'package:excel/excel.dart' as xl;
import 'package:flutter_test/flutter_test.dart';
import 'package:storely/models/product.dart';
import 'package:storely/utils/csv_importer.dart';

void main() {
  test('parses xlsx product rows from bytes', () async {
    final bytes = _xlsxBytes([
      ['Code', 'Name', 'Category', 'MRP', 'Quantity', 'Supplier'],
      ['A1', 'Notebook', 'Stationery', 55.5, 12, 'Acme'],
      ['B2', 'Pen', 'Stationery', 10, 40, 'Acme'],
    ]);

    final products = await CsvImporter.parseBytes(
      bytes,
      fileName: 'products.xlsx',
    );

    expect(products, hasLength(2));
    expect(products.first.itemCode, 'A1');
    expect(products.first.name, 'Notebook');
    expect(products.first.category, 'Stationery');
    expect(products.first.mrp, 55.5);
    expect(products.first.quantity, 12);
    expect(products.first.supplier, 'Acme');
    expect(products.first.source, ProductSource.imported);
  });

  test('finds xlsx headers below title rows', () async {
    final bytes = _xlsxBytes([
      ['Product upload sheet'],
      ['Generated by shop system'],
      ['Item Code', 'Product Name', 'MRP', 'Qty'],
      ['SKU-1', 'Rice Bag', 899, 3],
    ]);

    final products = await CsvImporter.parseBytes(
      bytes,
      fileName: 'picked-temp-file',
      extension: 'xlsx',
    );

    expect(products, hasLength(1));
    expect(products.single.itemCode, 'SKU-1');
    expect(products.single.name, 'Rice Bag');
    expect(products.single.mrp, 899);
    expect(products.single.quantity, 3);
  });

  test('falls back when package decoder crashes on workbook XML', () async {
    final products = await CsvImporter.parseBytes(
      _xlsxWithBrokenSharedString(),
      fileName: 'products.xlsx',
    );

    expect(products, hasLength(1));
    expect(products.single.itemCode, 'SKU-9');
    expect(products.single.name, 'Sugar');
    expect(products.single.mrp, 48);
    expect(products.single.quantity, 6);
  });

  test('reports unsupported legacy xls files clearly', () async {
    expect(
      () => CsvImporter.parseBytes(
        Uint8List.fromList([1, 2, 3]),
        fileName: 'products.xls',
      ),
      throwsA(
        isA<Exception>().having(
          (e) => e.toString(),
          'message',
          contains('Old .xls files are not supported'),
        ),
      ),
    );
  });
}

Uint8List _xlsxBytes(List<List<Object?>> rows) {
  final excel = xl.Excel.createExcel();
  final sheet = excel['Products'];
  excel.delete('Sheet1');

  for (final row in rows) {
    sheet.appendRow(row.map(_cellValue).toList());
  }

  return Uint8List.fromList(excel.save()!);
}

xl.CellValue? _cellValue(Object? value) {
  if (value == null) return null;
  if (value is int) return xl.IntCellValue(value);
  if (value is double) return xl.DoubleCellValue(value);
  if (value is bool) return xl.BoolCellValue(value);
  return xl.TextCellValue(value.toString());
}

Uint8List _xlsxWithBrokenSharedString() {
  final archive = Archive();
  _addTextFile(archive, '[Content_Types].xml', '''
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>
  <Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>
</Types>
''');
  _addTextFile(archive, 'xl/workbook.xml', '''
<workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"
    xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships">
  <sheets>
    <sheet name="Products" sheetId="1" r:id="rId1"/>
  </sheets>
</workbook>
''');
  _addTextFile(archive, 'xl/_rels/workbook.xml.rels', '''
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1"
      Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet"
      Target="worksheets/sheet1.xml"/>
</Relationships>
''');
  _addTextFile(archive, 'xl/worksheets/sheet1.xml', '''
<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
  <sheetData>
    <row r="1">
      <c r="A1" t="inlineStr"><is><t>Item Code</t></is></c>
      <c r="B1" t="inlineStr"><is><t>Product Name</t></is></c>
      <c r="C1" t="inlineStr"><is><t>MRP</t></is></c>
      <c r="D1" t="inlineStr"><is><t>Qty</t></is></c>
    </row>
    <row r="2">
      <c r="A2" t="inlineStr"><is><t>SKU-9</t></is></c>
      <c r="B2" t="inlineStr"><is><t>Sugar</t></is></c>
      <c r="C2"><v>48</v></c>
      <c r="D2"><v>6</v></c>
    </row>
    <row r="100">
      <c r="Z100" t="s"><v>99</v></c>
    </row>
  </sheetData>
</worksheet>
''');

  return Uint8List.fromList(ZipEncoder().encode(archive)!);
}

void _addTextFile(Archive archive, String path, String content) {
  final bytes = utf8.encode(content);
  archive.addFile(ArchiveFile(path, bytes.length, bytes));
}
