-- Storely production migration: bill invoice display toggles.
-- Safe to run on an existing Supabase project. It only adds missing columns
-- and keeps existing bill_settings rows/data.

alter table public.bill_settings
  add column if not exists show_invoice_title integer not null default 1,
  add column if not exists show_shop_name integer not null default 1,
  add column if not exists show_customer_name integer not null default 1,
  add column if not exists show_customer_gstin integer not null default 1,
  add column if not exists show_customer_legal_name integer not null default 1,
  add column if not exists show_customer_trade_name integer not null default 1,
  add column if not exists show_customer_place_of_supply integer not null default 1,
  add column if not exists show_invoice_number integer not null default 1,
  add column if not exists show_invoice_date integer not null default 1,
  add column if not exists show_invoice_place_of_supply integer not null default 1,
  add column if not exists show_invoice_supply_type integer not null default 1,
  add column if not exists show_item_serial_column integer not null default 1,
  add column if not exists show_item_name_column integer not null default 1,
  add column if not exists show_quantity_column integer not null default 1,
  add column if not exists show_rate_column integer not null default 1,
  add column if not exists show_gst_percent_column integer not null default 1,
  add column if not exists show_gst_amount_column integer not null default 1,
  add column if not exists show_amount_column integer not null default 1,
  add column if not exists show_subtotal integer not null default 1,
  add column if not exists show_discount integer not null default 1,
  add column if not exists show_taxable_amount integer not null default 1,
  add column if not exists show_cgst_sgst_igst integer not null default 1,
  add column if not exists show_gst_total integer not null default 1,
  add column if not exists show_grand_total integer not null default 1,
  add column if not exists show_footer_text integer not null default 1;

update public.bill_settings
set
  show_invoice_title = coalesce(show_invoice_title, 1),
  show_shop_name = coalesce(show_shop_name, 1),
  show_customer_name = coalesce(show_customer_name, 1),
  show_customer_gstin = coalesce(show_customer_gstin, 1),
  show_customer_legal_name = coalesce(show_customer_legal_name, 1),
  show_customer_trade_name = coalesce(show_customer_trade_name, 1),
  show_customer_place_of_supply = coalesce(show_customer_place_of_supply, 1),
  show_invoice_number = coalesce(show_invoice_number, 1),
  show_invoice_date = coalesce(show_invoice_date, 1),
  show_invoice_place_of_supply = coalesce(show_invoice_place_of_supply, 1),
  show_invoice_supply_type = coalesce(show_invoice_supply_type, 1),
  show_item_serial_column = coalesce(show_item_serial_column, 1),
  show_item_name_column = coalesce(show_item_name_column, 1),
  show_quantity_column = coalesce(show_quantity_column, 1),
  show_rate_column = coalesce(show_rate_column, 1),
  show_gst_percent_column = coalesce(show_gst_percent_column, 1),
  show_gst_amount_column = coalesce(show_gst_amount_column, 1),
  show_amount_column = coalesce(show_amount_column, 1),
  show_subtotal = coalesce(show_subtotal, 1),
  show_discount = coalesce(show_discount, 1),
  show_taxable_amount = coalesce(show_taxable_amount, 1),
  show_cgst_sgst_igst = coalesce(show_cgst_sgst_igst, 1),
  show_gst_total = coalesce(show_gst_total, 1),
  show_grand_total = coalesce(show_grand_total, 1),
  show_footer_text = coalesce(show_footer_text, 1);
